module PlotterControl.Interop.Status.Encode exposing (..)

{-| Generated by <https://github.com/pravdomil/Elm-JSON-Interop>.
-}

import PlotterControl.Interop.Status as A 
import Json.Encode as E 
import Utils.Json.Encode_ as E_ exposing (Encoder)

status : Encoder A.Status
status  =
    \v1 -> 
    case v1 of
      A.Ready  ->
        (E.object) ([("a", (E.int) (0))])
      A.Connecting  ->
        (E.object) ([("a", (E.int) (1))])
      A.Busy  ->
        (E.object) ([("a", (E.int) (2))])
      A.Error v2 ->
        (E.object) ([("a", (E.int) (3)), ("b", ((error)) (v2))])
    

error : Encoder A.Error
error  =
    \v1 -> 
    case v1 of
      A.OpenError  ->
        (E.object) ([("a", (E.int) (0))])
      A.WriterError  ->
        (E.object) ([("a", (E.int) (1))])
      A.WriteError  ->
        (E.object) ([("a", (E.int) (2))])
      A.DecodeError v2 ->
        (E.object) ([("a", (E.int) (3)), ("b", ((E.string)) (v2))])
    