module PlotterControl.Interop.Decode exposing (..)

{-| Generated by <https://github.com/pravdomil/Elm-JSON-Interop>.
-}

import PlotterControl.Interop as A 
import Json.Decode as D exposing (Decoder)
import Utils.Json.Decode_ as D_ 
import Json.Decode.Decode  

status : Decoder A.Status
status  =
    (D.lazy) (\_ -> (D.field) ("a") (D.int) |> (D.andThen) (\a___ -> 
    case a___ of
      0 ->
        (D.succeed) (A.Ready)
      1 ->
        (D.succeed) (A.Connecting)
      2 ->
        (D.succeed) (A.Busy)
      3 ->
        (D.map) (A.Error) ((D.field) ("b") ((error)))
      _ ->
        (D.fail) ("I can't decode \"Status\", unknown variant with index " ++ (String.fromInt) (a___) ++ ".")
    ))

error : Decoder A.Error
error  =
    (D.lazy) (\_ -> (D.field) ("a") (D.int) |> (D.andThen) (\a___ -> 
    case a___ of
      0 ->
        (D.succeed) (A.OpenError)
      1 ->
        (D.succeed) (A.WriterError)
      2 ->
        (D.succeed) (A.WriteError)
      3 ->
        (D.map) (A.DecodeError) ((D.field) ("b") ((Json.Decode.Decode.error)))
      _ ->
        (D.fail) ("I can't decode \"Error\", unknown variant with index " ++ (String.fromInt) (a___) ++ ".")
    ))